void setupGame();
void setupMap();
void setupPlayer();
void gameLoop();
void updateDir(unsigned char dir, unsigned char mv);
void updatePlayer();
void movePlayer(unsigned char dir);
void makePlayer();
void makeItemLists();
void makeQuest();
void makeStats();
bool checkPlayerExists();
void getItemLists();
void getQuests();
void getStats();
void postStats();
void setupItems();
char getch();
std::string getexepath();
